In [4]:
import numpy as np
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [12]:
a=np.array([(1,2,3,4),(5,6,7,8.9)],dtype=float)
print (a)
a.shape

[[1.  2.  3.  4. ]
 [5.  6.  7.  8.9]]


(2, 4)

In [25]:
b=np.full((5,5),0)
print(b)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [23]:
# identity matrix
x=np.eye(5)
print (x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [30]:
#random numbers
y=np.random.random((4,5))
print(y)

[[0.14112464 0.55699626 0.32120136 0.01356276 0.61030734]
 [0.0020734  0.08348405 0.2525089  0.64673069 0.07835379]
 [0.07284216 0.24419991 0.45857081 0.17297258 0.9671526 ]
 [0.79940785 0.48861757 0.90340269 0.30794967 0.6168195 ]]


In [39]:
y=np.random.randint(1,100,(4,5))
print(y)

[[47 54 95 61 24]
 [20 77 22 60 92]
 [26 17 17 41 91]
 [75 19 84 26 68]]


In [47]:
#Evenly spaced
e = np.linspace(10,50,7)
print(e)

[10.         16.66666667 23.33333333 30.         36.66666667 43.33333333
 50.        ]


In [46]:
e = np.arange(10,50,10)
print(e)

[10 20 30 40]


In [49]:
#convert list to numpy array
list2=[10,20,30,40,50]

np_array=np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

In [51]:
#Analyzing numpy
m=np.random.randint(10,100,(5,5))
print(m)

[[77 36 42 44 44]
 [38 41 23 47 21]
 [21 11 97 40 79]
 [69 66 16 93 72]
 [93 92 22 77 46]]


In [53]:
#dimension 
print(m.shape)

(5, 5)


In [54]:
#number of values 
print(m.size)

25


In [55]:
#datatype
print(m.dtype)

int32


In [56]:
#Mathematical operations
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)


[[2 3 1]
 [4 9 2]
 [2 6 6]]
[[12 17 13]
 [14 15 14]
 [10 10 15]]


In [58]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)



[[14 20 14]
 [18 24 16]
 [12 16 21]]
[[-10 -14 -12]
 [-10  -6 -12]
 [ -8  -4  -9]]
[[ 24  51  13]
 [ 56 135  28]
 [ 20  60  90]]
[[0.16666667 0.17647059 0.07692308]
 [0.28571429 0.6        0.14285714]
 [0.2        0.6        0.4       ]]


In [59]:
#Another way of doing
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[14 20 14]
 [18 24 16]
 [12 16 21]]
[[-10 -14 -12]
 [-10  -6 -12]
 [ -8  -4  -9]]
[[ 24  51  13]
 [ 56 135  28]
 [ 20  60  90]]
[[0.16666667 0.17647059 0.07692308]
 [0.28571429 0.6        0.14285714]
 [0.2        0.6        0.4       ]]


In [61]:
#Array manipulation
#Transpose
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[8 7 7]
 [2 3 2]]
(2, 3)


In [62]:
#Finding the transpose
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[8 2]
 [7 3]
 [7 2]]
(3, 2)


In [63]:
#Reshaping array
r=np.random.randint(0,10,(3,4))
print(r)
print(r.shape)

[[3 3 6 7]
 [3 7 0 2]
 [2 9 6 2]]
(3, 4)


In [66]:
re=r.reshape(4,3)
print(re)
print(re.shape)

[[3 3 6]
 [7 3 7]
 [0 2 2]
 [9 6 2]]
(4, 3)
